name       : akonadi-search
version    : 19.04.3
release    : 26
source     :
    - https://cdn.download.kde.org/stable/applications/19.04.3/src/akonadi-search-19.04.3.tar.xz : c5298a5b903373590e63039777c954720aa0bc46b25ec0c48e6409265b38d4ed
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
component  : desktop.library
summary    : Libraries and daemons to implement searching in Akonadi
description: |
    Libraries and daemons to implement searching in Akonadi.
builddeps  :
    - pkgconfig(Qt5Core)
    - pkgconfig(xapian-core)
    - akonadi-devel
    - akonadi-mime-devel
    - extra-cmake-modules
    - kcalcore-devel
    - kcmutils-devel
    - kcompletion-devel
    - kcontacts-devel
    - kcrash-devel
    - kdelibs4support-devel
    - ki18n-devel
    - kitemmodels-devel
    - kmime-devel
    - krunner-devel
    - kxmlgui-devel
    - libboost-devel
    - libical-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
