name       : akonadi-search
version    : 18.08.3
release    : 17
source     :
    - https://cdn.download.kde.org/stable/applications/18.08.3/src/akonadi-search-18.08.3.tar.xz : 599203bedf749cd5e824f374c9aeaadbc0dcde38a28f567c6117e1929fc6763e
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
component  : desktop.library
summary    : Libraries and daemons to implement searching in Akonadi
description: |
    Libraries and daemons to implement searching in Akonadi.
builddeps  :
    - pkgconfig(Qt5Core)
    - pkgconfig(xapian-core)
    - akonadi-devel
    - akonadi-mime-devel
    - extra-cmake-modules
    - kcalcore-devel
    - kcmutils-devel
    - kcompletion-devel
    - kcontacts-devel
    - kcrash-devel
    - kdelibs4support-devel
    - ki18n-devel
    - kitemmodels-devel
    - kmime-devel
    - krunner-devel
    - kxmlgui-devel
    - libboost-devel
    - libical-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
