name       : akonadi-search
version    : 19.04.2
release    : 25
source     :
    - https://cdn.download.kde.org/stable/applications/19.04.2/src/akonadi-search-19.04.2.tar.xz : 46a6b01c363172b5de389f3dbdd9e3518abed381663e6854562dc910d3b4aa45
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
component  : desktop.library
summary    : Libraries and daemons to implement searching in Akonadi
description: |
    Libraries and daemons to implement searching in Akonadi.
builddeps  :
    - pkgconfig(Qt5Core)
    - pkgconfig(xapian-core)
    - akonadi-devel
    - akonadi-mime-devel
    - extra-cmake-modules
    - kcalcore-devel
    - kcmutils-devel
    - kcompletion-devel
    - kcontacts-devel
    - kcrash-devel
    - kdelibs4support-devel
    - ki18n-devel
    - kitemmodels-devel
    - kmime-devel
    - krunner-devel
    - kxmlgui-devel
    - libboost-devel
    - libical-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
