name       : akonadi-search
version    : 18.04.1
release    : 11
source     :
    - https://cdn.download.kde.org/stable/applications/18.04.1/src/akonadi-search-18.04.1.tar.xz : 5463f92b61641cf3fe63076580a3abee2e5db3931412b99764b3f439f491ae06
license    : LGPL-2.1
component  : desktop.library
optimize   : lto
summary    : Libraries and daemons to implement searching in Akonadi.
description: |
    Libraries and daemons to implement searching in Akonadi.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Core)
    - pkgconfig(xapian-core)
    - akonadi-devel
    - akonadi-mime-devel
    - extra-cmake-modules
    - kcalcore-devel
    - kcmutils-devel
    - kcompletion-devel
    - kcontacts-devel
    - kcrash-devel
    - kdelibs4support-devel
    - ki18n-devel
    - kitemmodels-devel
    - kmime-devel
    - krunner-devel
    - kxmlgui-devel
    - libboost-devel
    - libical-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
