name       : akonadi-search
version    : 20.12.2
release    : 50
source     :
    - https://cdn.download.kde.org/stable/release-service/20.12.2/src/akonadi-search-20.12.2.tar.xz : 4a96b8e96b4e195d73f3ab5f7fb742c94f1c7bad6fdd784b4301c867843bf454
homepage   : https://kde.org/
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
component  : desktop.library
summary    : Libraries and daemons to implement searching in Akonadi
description: |
    Libraries and daemons to implement searching in Akonadi.
builddeps  :
    - pkgconfig(xapian-core)
    - akonadi-mime-devel
    - kcalendarcore-devel
    - kcmutils-devel
    - kcontacts-devel
    - kcrash-devel
    - kdbusaddons-devel
    - kio-devel
    - kitemmodels-devel
    - krunner-devel
    - libboost-devel
rundeps    :
    - devel :
        - akonadi-devel
        - kcalendarcore-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
