name       : akonadi-search
version    : 21.12.0
release    : 60
source     :
    - https://cdn.download.kde.org/stable/release-service/21.12.0/src/akonadi-search-21.12.0.tar.xz : 3305dea1b1c1844fd15dc2cc3a631264beb9b00106e62ddfbecd260c41feca1d
homepage   : https://kde.org/
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
component  : desktop.library
summary    : Libraries and daemons to implement searching in Akonadi
description: |
    Libraries and daemons to implement searching in Akonadi.
builddeps  :
    - pkgconfig(xapian-core)
    - akonadi-mime-devel
    - kcalendarcore-devel
    - kcmutils-devel
    - kcontacts-devel
    - kcrash-devel
    - kdbusaddons-devel
    - kio-devel
    - kitemmodels-devel
    - krunner-devel
    - libboost-devel
rundeps    :
    - devel :
        - akonadi-devel
        - kcalendarcore-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
