name       : akonadi-search
version    : 21.04.3
release    : 55
source     :
    - https://cdn.download.kde.org/stable/release-service/21.04.3/src/akonadi-search-21.04.3.tar.xz : d047ef7b4a338dd31bce4d22b5c4bc8c9e87d1067d581afaa8549e7074f1c69b
homepage   : https://kde.org/
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
component  : desktop.library
summary    : Libraries and daemons to implement searching in Akonadi
description: |
    Libraries and daemons to implement searching in Akonadi.
builddeps  :
    - pkgconfig(xapian-core)
    - akonadi-mime-devel
    - kcalendarcore-devel
    - kcmutils-devel
    - kcontacts-devel
    - kcrash-devel
    - kdbusaddons-devel
    - kio-devel
    - kitemmodels-devel
    - krunner-devel
    - libboost-devel
rundeps    :
    - devel :
        - akonadi-devel
        - kcalendarcore-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
