name       : akonadi-search
version    : 19.12.2
release    : 36
source     :
    - https://cdn.download.kde.org/stable/release-service/19.12.2/src/akonadi-search-19.12.2.tar.xz : bf08eac2ada3bc01a501c35e31b01fb4de9a456b3c877cbb10d8529880e9f753
homepage   : https://kde.org/
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
component  : desktop.library
summary    : Libraries and daemons to implement searching in Akonadi
description: |
    Libraries and daemons to implement searching in Akonadi.
builddeps  :
    - pkgconfig(Qt5Core)
    - pkgconfig(xapian-core)
    - akonadi-devel
    - akonadi-mime-devel
    - extra-cmake-modules
    - kcmutils-devel
    - kcontacts-devel
    - kcrash-devel
    - kdbusaddons-devel
    - ki18n-devel
    - kio-devel
    - kitemmodels-devel
    - kmime-devel
    - krunner-devel
    - libboost-devel
    - libical-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
