name       : akonadi-search
version    : 21.04.2
release    : 54
source     :
    - https://cdn.download.kde.org/stable/release-service/21.04.2/src/akonadi-search-21.04.2.tar.xz : e5e9d2241a3397fa445bc55fbdc8f080c4a3c79d380b834ad9c3d3d311d9735f
homepage   : https://kde.org/
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
component  : desktop.library
summary    : Libraries and daemons to implement searching in Akonadi
description: |
    Libraries and daemons to implement searching in Akonadi.
builddeps  :
    - pkgconfig(xapian-core)
    - akonadi-mime-devel
    - kcalendarcore-devel
    - kcmutils-devel
    - kcontacts-devel
    - kcrash-devel
    - kdbusaddons-devel
    - kio-devel
    - kitemmodels-devel
    - krunner-devel
    - libboost-devel
rundeps    :
    - devel :
        - akonadi-devel
        - kcalendarcore-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
