name       : akonadi-search
version    : 18.04.3
release    : 13
source     :
    - https://cdn.download.kde.org/stable/applications/18.04.3/src/akonadi-search-18.04.3.tar.xz : 4360878893c9bf8ed49b4af294954d35d3b2183d29eaa5d40f02e0fcc9234995
license    : LGPL-2.1
component  : desktop.library
summary    : Libraries and daemons to implement searching in Akonadi
description: |
    Libraries and daemons to implement searching in Akonadi.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Core)
    - pkgconfig(xapian-core)
    - akonadi-devel
    - akonadi-mime-devel
    - extra-cmake-modules
    - kcalcore-devel
    - kcmutils-devel
    - kcompletion-devel
    - kcontacts-devel
    - kcrash-devel
    - kdelibs4support-devel
    - ki18n-devel
    - kitemmodels-devel
    - kmime-devel
    - krunner-devel
    - kxmlgui-devel
    - libboost-devel
    - libical-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
