name       : akonadi-search
version    : 17.12.1
release    : 6
source     :
    - https://cdn.download.kde.org/stable/applications/17.12.1/src/akonadi-search-17.12.1.tar.xz : 5717a6ba8b812273f85a83c9f86f0f4016759add247c0e556dd88ccf58e77491
license    : LGPL-2.1
component  : desktop.library
summary    : Libraries and daemons to implement searching in Akonadi.
description: |
    Libraries and daemons to implement searching in Akonadi.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Core)
    - pkgconfig(xapian-core)
    - akonadi-devel
    - akonadi-mime-devel
    - extra-cmake-modules
    - kcalcore-devel
    - kcmutils-devel
    - kcompletion-devel
    - kcontacts-devel
    - kcrash-devel
    - kdelibs4support-devel
    - ki18n-devel
    - kitemmodels-devel
    - kmime-devel
    - krunner-devel
    - kxmlgui-devel
    - libboost-devel
    - libical-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
