name       : akonadi-search
version    : 21.12.3
release    : 62
source     :
    - https://cdn.download.kde.org/stable/release-service/21.12.3/src/akonadi-search-21.12.3.tar.xz : d76c0edccf2e25b9e86469d21a32015315e77cb05f489fc3bffb27d6e5ffa6c5
homepage   : https://kde.org/
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
component  : desktop.library
summary    : Libraries and daemons to implement searching in Akonadi
description: |
    Libraries and daemons to implement searching in Akonadi.
builddeps  :
    - pkgconfig(xapian-core)
    - akonadi-mime-devel
    - kcalendarcore-devel
    - kcmutils-devel
    - kcontacts-devel
    - kcrash-devel
    - kdbusaddons-devel
    - kio-devel
    - kitemmodels-devel
    - krunner-devel
    - libboost-devel
rundeps    :
    - devel :
        - akonadi-devel
        - kcalendarcore-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
