name       : akonadi-search
version    : 17.08.3
release    : 5
source     :
    - https://cdn.download.kde.org/stable/applications/17.08.3/src/akonadi-search-17.08.3.tar.xz : 99e10afbc7058fc54327ea36823bd177627dc28672b346da1400e6189ad8a699
license    : LGPL-2.1
component  : desktop.library
summary    : Libraries and daemons to implement searching in Akonadi.
description: |
    Libraries and daemons to implement searching in Akonadi.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Core)
    - pkgconfig(xapian-core)
    - akonadi-devel
    - akonadi-mime-devel
    - extra-cmake-modules
    - kcalcore-devel
    - kcmutils-devel
    - kcompletion-devel
    - kcontacts-devel
    - kcrash-devel
    - kdelibs4support-devel
    - ki18n-devel
    - kitemmodels-devel
    - kmime-devel
    - krunner-devel
    - kxmlgui-devel
    - libboost-devel
    - libical-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
